# Generated by Django 4.1.3 on 2022-11-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="nickname",
            field=models.CharField(default="超值二手機", max_length=50),
        ),
    ]
