# Generated by Django 4.1.3 on 2022-11-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0002_alter_product_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pphoto",
            name="description",
            field=models.CharField(default="產品照片", max_length=200),
        ),
    ]
