# Generated by Django 4.1.3 on 2022-11-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="car_list",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "car_maker",
                    models.CharField(
                        choices=[
                            ("Ford", "Ford"),
                            ("Honda", "Honda"),
                            ("Mazda", "Mazda"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "car_model",
                    models.CharField(
                        choices=[
                            ("Fiesta", "Fiesta"),
                            ("Focus", "Focus"),
                            ("Mustang", "Mustang"),
                            ("Fit", "Fit"),
                            ("City", "City"),
                            ("NSX", "NSX"),
                            ("Mazda3", "Mazda3"),
                            ("Mazda5", "Mazda5"),
                            ("Mazda6", "Mazda6"),
                        ],
                        max_length=20,
                    ),
                ),
                ("car_price", models.IntegerField()),
                ("car_qty", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="engtv_list",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tvno", models.IntegerField()),
                ("tvname", models.CharField(max_length=20)),
                ("tvcode", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="tv_list",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tvno", models.IntegerField()),
                ("tvname", models.CharField(max_length=20)),
                ("tvcode", models.CharField(max_length=20)),
            ],
        ),
    ]
