# Generated by Django 4.1.3 on 2022-11-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainsite", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car_list",
            name="car_maker",
            field=models.CharField(
                choices=[
                    (
                        "Ford",
                        (
                            ("Fiesta", "Fiesta"),
                            ("Focus", "Focus"),
                            ("Mustang", "Mustang"),
                        ),
                    ),
                    ("Honda", (("Fit", "Fit"), ("City", "City"), ("NSX", "NSX"))),
                    (
                        "Mazda",
                        (
                            ("Mazda3", "Mazda3"),
                            ("Mazda5", "Mazda5"),
                            ("Mazda6", "Mazda6"),
                        ),
                    ),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="car_list",
            name="car_model",
            field=models.CharField(
                choices=[
                    (
                        "Ford",
                        (
                            ("Fiesta", "Fiesta"),
                            ("Focus", "Focus"),
                            ("Mustang", "Mustang"),
                        ),
                    ),
                    ("Honda", (("Fit", "Fit"), ("City", "City"), ("NSX", "NSX"))),
                    (
                        "Mazda",
                        (
                            ("Mazda3", "Mazda3"),
                            ("Mazda5", "Mazda5"),
                            ("Mazda6", "Mazda6"),
                        ),
                    ),
                ],
                max_length=20,
            ),
        ),
    ]
