# Generated by Django 4.1.3 on 2022-11-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainsite", "0002_alter_car_list_car_maker_alter_car_list_car_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car_list",
            name="car_maker",
            field=models.CharField(
                choices=[("Ford", "Ford"), ("Honda", "Honda"), ("Mazda", "Mazda")],
                max_length=20,
            ),
        ),
    ]
