# Generated by Django 4.1.3 on 2022-11-05 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainsite", "0003_alter_car_list_car_maker"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="engtv_list",
            name="tvno",
        ),
    ]
