# Generated by Django 4.1.3 on 2022-11-06 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainsite", "0006_rename_car_model_car_list_car_list"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car_list",
            old_name="car_list",
            new_name="car_model",
        ),
    ]
