# Generated by Django 3.2 on 2022-10-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.URLField(default='https://cdn.sao-x.com/cover/084.webp', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='depiction',
            field=models.CharField(default='不知道要說什麼的摘要', max_length=200),
            preserve_default=False,
        ),
    ]
